/// Converts the snake_case rows returned by the Postgres `pumps` and
/// `pump_daily_uploads` tables into the camelCase shape the pump screens
/// were originally written against when they read Firestore documents.
/// Keeping these mappings centralized avoids re-deriving the ~35-field
/// upload shape independently in every screen that reads uploads.
library;

Map<String, dynamic> pumpRowToJson(Map<String, dynamic> row) => {
      'id': row['id'],
      'pumpNumber': row['pump_number'],
      'productId': row['product_id'],
      'productName': row['product_name'],
      'productUnit': row['product_unit'],
      'productPrice': row['product_price'],
      'model': row['model'],
      'serialNumber': row['serial_number'],
      'manufacturer': row['manufacturer'],
      'manufactureYear': row['manufacture_year'],
      'isActive': row['is_active'],
    };

Map<String, dynamic> pumpUploadRowToJson(Map<String, dynamic> row) => {
      'id': row['id'],
      'pumpId': row['pump_id'],
      'pumpNumber': row['pump_number'],
      'productId': row['product_id'],
      'productName': row['product_name'],
      'productUnit': row['product_unit'],
      'productPrice': row['product_price'],
      'openingVolume': row['opening_volume'],
      'closingVolume': row['closing_volume'],
      'digitalVolume': row['digital_volume'],
      'volumeDifference': row['volume_difference'],
      'analogOpeningVolume': row['analog_opening_volume'],
      'analogClosingVolume': row['analog_closing_volume'],
      'soldVolume': row['sold_volume'],
      'cashDerivedVolume': row['cash_derived_volume'],
      'previousAnalogClosingVolume': row['previous_analog_closing_volume'],
      'previousShiftClosingCash': row['previous_shift_closing_cash'],
      'previousClosingVolume': row['previous_closing_volume'],
      'expectedAmount': row['expected_amount'],
      'shiftOpeningCash': row['shift_opening_cash'],
      'shiftCloseCash': row['shift_close_cash'],
      'shiftCashDifference': row['shift_cash_difference'],
      'todayPumpCash': row['today_pump_cash'],
      'cashAmount': row['cash_amount'],
      'cashBreakdown': row['cash_breakdown'],
      'posAmount': row['pos_amount'],
      'totalPaid': row['total_paid'],
      'discrepancyNotes': row['discrepancy_notes'],
      'discrepancySummary': row['discrepancy_summary'],
      'uploadFingerprint': row['upload_fingerprint'],
      'saleId': row['sale_id'],
      'workerId': row['worker_id'],
      'workerName': row['worker_name'],
      'shiftOpeningCashPhotoUrl': row['shift_opening_cash_photo_url'],
      'shiftCloseCashPhotoUrl': row['shift_close_cash_photo_url'],
      'openingPhotoUrl': row['opening_photo_url'],
      'closingPhotoUrl': row['closing_photo_url'],
      'isDisputed': row['is_disputed'],
      'disputedAt': row['disputed_at'],
      'disputedBy': row['disputed_by'],
      'disputedByName': row['disputed_by_name'],
      'disputeReason': row['dispute_reason'],
      'disputeResolvedAt': row['dispute_resolved_at'],
      'disputeResolvedBy': row['dispute_resolved_by'],
      'disputeResolvedByName': row['dispute_resolved_by_name'],
      'uploadedAt': row['uploaded_at'],
      'createdAt': row['created_at'],
      'category': row['category'],
    };

Map<String, dynamic> pumpUploadAdjustmentRowToJson(Map<String, dynamic> row) => {
      'id': row['id'],
      'uploadId': row['upload_id'],
      'pumpId': row['pump_id'],
      'pumpNumber': row['pump_number'],
      'productName': row['product_name'],
      'uploadedAt': row['uploaded_at'],
      'action': row['action'],
      'changes': row['changes'],
      'note': row['note'],
      'adjustedBy': row['adjusted_by'],
      'adjustedByName': row['adjusted_by_name'],
      'adjustedAt': row['adjusted_at'],
    };
