import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';

class ReceiptAssetService {
  static Future<Uint8List> generateReceiptImage({
    required String businessName,
    required String receiptText,
    String? receiptNumber,
    String title = 'RECEIPT',
  }) async {
    final normalizedText = receiptText.replaceAll('\r\n', '\n').trim();
    final lines = normalizedText.isEmpty
        ? const <String>['Receipt unavailable']
        : normalizedText.split('\n');

    const width = 720.0;
    const cardInset = 18.0;
    const horizontalPadding = 32.0;
    const headerHeight = 132.0;
    final bodyWidth = width - ((cardInset + horizontalPadding) * 2);

    final businessPainter = _buildPainter(
      text: businessName,
      maxWidth: bodyWidth,
      textAlign: TextAlign.center,
      style: const TextStyle(
        color: Colors.white,
        fontSize: 28,
        fontWeight: FontWeight.w800,
        letterSpacing: -0.4,
      ),
    );

    final titlePainter = _buildPainter(
      text: receiptNumber == null || receiptNumber.isEmpty
          ? title
          : '$title  #$receiptNumber',
      maxWidth: bodyWidth,
      textAlign: TextAlign.center,
      style: const TextStyle(
        color: Color(0xFFE2E8F0),
        fontSize: 14,
        fontWeight: FontWeight.w600,
        letterSpacing: 1,
      ),
    );

    final linePainters = lines
        .map(
          (line) => _buildPainter(
            text: line.isEmpty ? ' ' : line,
            maxWidth: bodyWidth,
            style: const TextStyle(
              color: Color(0xFF0F172A),
              fontSize: 18,
              height: 1.45,
              fontFamily: 'monospace',
            ),
          ),
        )
        .toList();

    final footerPainter = _buildPainter(
      text: 'Generated by Manage Care',
      maxWidth: bodyWidth,
      textAlign: TextAlign.center,
      style: const TextStyle(
        color: Color(0xFF64748B),
        fontSize: 13,
        fontWeight: FontWeight.w600,
      ),
    );

    var bodyHeight = 0.0;
    for (final painter in linePainters) {
      bodyHeight += painter.height + 6;
    }

    final height = cardInset +
        headerHeight +
        28 +
        bodyHeight +
        18 +
        footerPainter.height +
        28 +
        cardInset;

    final recorder = ui.PictureRecorder();
    final canvas = Canvas(recorder);
    final size = Size(width, height);

    canvas.drawRect(
      Offset.zero & size,
      Paint()..color = const Color(0xFFF1F5F9),
    );

    final cardRect = RRect.fromRectAndRadius(
      Rect.fromLTWH(
        cardInset,
        cardInset,
        width - (cardInset * 2),
        height - (cardInset * 2),
      ),
      const Radius.circular(24),
    );

    canvas.drawShadow(
      Path()..addRRect(cardRect),
      Colors.black.withOpacity(0.12),
      16,
      true,
    );
    canvas.drawRRect(cardRect, Paint()..color = Colors.white);

    final headerRect = Rect.fromLTWH(
      cardInset,
      cardInset,
      width - (cardInset * 2),
      headerHeight,
    );
    final headerRRect = RRect.fromRectAndCorners(
      headerRect,
      topLeft: const Radius.circular(24),
      topRight: const Radius.circular(24),
      bottomLeft: const Radius.circular(18),
      bottomRight: const Radius.circular(18),
    );
    canvas.drawRRect(
      headerRRect,
      Paint()
        ..shader = const LinearGradient(
          colors: [
            Color(0xFF2563EB),
            Color(0xFF1E3A8A),
          ],
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
        ).createShader(headerRect),
    );

    businessPainter.paint(
      canvas,
      Offset(
        (width - businessPainter.width) / 2,
        cardInset + 32,
      ),
    );
    titlePainter.paint(
      canvas,
      Offset(
        (width - titlePainter.width) / 2,
        cardInset + 78,
      ),
    );

    var y = cardInset + headerHeight + 28;
    canvas.drawLine(
      Offset(cardInset + 24, y - 10),
      Offset(width - cardInset - 24, y - 10),
      Paint()
        ..color = const Color(0xFFE2E8F0)
        ..strokeWidth = 1,
    );

    for (final painter in linePainters) {
      painter.paint(canvas, Offset(cardInset + horizontalPadding, y));
      y += painter.height + 6;
    }

    canvas.drawLine(
      Offset(cardInset + 24, y + 2),
      Offset(width - cardInset - 24, y + 2),
      Paint()
        ..color = const Color(0xFFE2E8F0)
        ..strokeWidth = 1,
    );

    footerPainter.paint(
      canvas,
      Offset(
        (width - footerPainter.width) / 2,
        y + 18,
      ),
    );

    final image = await recorder
        .endRecording()
        .toImage(width.ceil(), height.ceil());
    final byteData = await image.toByteData(format: ui.ImageByteFormat.png);
    image.dispose();

    if (byteData == null) {
      throw StateError('Failed to render receipt image.');
    }

    return byteData.buffer.asUint8List();
  }

  static TextPainter _buildPainter({
    required String text,
    required double maxWidth,
    required TextStyle style,
    TextAlign textAlign = TextAlign.left,
  }) {
    final painter = TextPainter(
      text: TextSpan(text: text, style: style),
      textDirection: TextDirection.ltr,
      textAlign: textAlign,
    )..layout(maxWidth: maxWidth);
    return painter;
  }
}
