// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBR-KdYr8jtTjatQgrdNNtGRcGIAQYgaXA",
      authDomain: "manage-care-1e96b.firebaseapp.com",
      databaseURL: "https://manage-care-1e96b-default-rtdb.firebaseio.com",
      projectId: "manage-care-1e96b",
      storageBucket: "manage-care-1e96b.firebasestorage.app",
      messagingSenderId: "481744910720",
      appId: "1:481744910720:web:8ee6d70263346747b92965",
      measurementId: "G-DZ3CE9LWYT");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxaqlfcndDWnEXJuAWJ1Q41nS3-2-1vvU',
    appId: '1:481744910720:android:4a5d7debd6070c03b92965',
    messagingSenderId: '481744910720',
    projectId: 'manage-care-1e96b',
    databaseURL: 'https://manage-care-1e96b-default-rtdb.firebaseio.com',
    storageBucket: 'manage-care-1e96b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOXPuCuqlOBB5TdNnRD6WX0nwBYK2e2aA',
    appId: '1:481744910720:ios:c07e1173350499b8b92965',
    messagingSenderId: '481744910720',
    projectId: 'manage-care-1e96b',
    databaseURL: 'https://manage-care-1e96b-default-rtdb.firebaseio.com',
    storageBucket: 'manage-care-1e96b.firebasestorage.app',
    iosBundleId: 'com.managecare',
  );
}

